# rake mac_and_cheese

# Pass values to the functions
# :symbol => value

task :mac_and_cheese => [:boil_water, :buy_pasta, :buy_cheese] do
    p "Making Mac and Cheese"
end

task :buy_cheese do
    p "Buying cheese"
end

task :buy_pasta do
    p "Buying Pasta"
end

task :boil_water => [:buy_cheese, :buy_pasta] do
    p "Boilling Water"
end